name: Run Spring Boot App

on:
  push:
    branches: [ "master" ]

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build app
        run: ./mvnw clean package -DskipTests

      - name: Start app
        run: |
          nohup java -jar target/*.jar > app.log 2>&1 &
          sleep 30

      - name: Check app
        run: curl -f http://localhost:8080 || (echo "App not responding" && exit 1)

      - name: Show logs (debug)
        run: cat app.log